%definiendum och definiens av konstanter
%% Different N
L = 10;
v=[0 0.1 0.5 1 10]; N=[10 20 40 80];

f1 = figure;
for i = 1:4
    [A, b] = matrix_builder(N(i), v(3));
    u = A\b;
    u = vertcat(400, u);
    z = linspace(0, L, N(i)+1);
    plot(z, u)
    hold on
end

axis([0,L,200,600])
set(gca,...
    'Units','normalized',...
    'YTick',200:100:600,...
    'XTick',0:2:10,...  
    'FontUnits','points',...    
    'FontWeight','normal',...
    'FontSize',10,...
    'FontName','Times')
ylabel({'Temperature (K)'},...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times')
xlabel('Length (L)',...
    'FontUnits','points',...
    'interpreter','latex',...   
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
legend({'$N = 10$', '$N = 20$', '$N = 40$', '$N = 80$'},...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times',...
    'Location','NorthEast')
print -depsc2 out/heat-plot-different-N.eps

%% Different v

L = 10;
v=[0.1 0.5 1 10]; N=[10 20 40 80];

f2 = figure;
for i = 1:4
    [A, b] = matrix_builder(N(3), v(i));
    u = A\b;
    u = vertcat(400, u);
    z = linspace(0, L, N(3)+1);
    plot(z, u)
    hold on
end

axis([0,L,200,600])
set(gca,...
    'Units','normalized',...
    'YTick',200:100:600,...
    'XTick',0:2:10,...  
    'FontUnits','points',...    
    'FontWeight','normal',...
    'FontSize',10,...
    'FontName','Times')
ylabel({'Temperature (K)'},...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times')
xlabel('Length (L)',...
    'FontUnits','points',...
    'interpreter','latex',...   
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
legend({'$v = 0.1$', '$v = 0.5$', '$v = 1$', '$v = 10$'},...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times',...
    'Location','NorthEast')
print -depsc2 out/heat-plot-different-velocities.eps

%% Oscillations, different N
L = 10;
v=[0 0.1 0.5 1 10]; N=[10 20 40 80];

f3 = figure;
for i = 1:4
    [A, b] = matrix_builder(N(i), v(5));
    u = A\b;
    u = vertcat(400, u);
    z = linspace(0, L, N(i)+1);
    plot(z, u)
    hold on
end

axis([0,L,200,600])
set(gca,...
    'Units','normalized',...
    'YTick',200:100:600,...
    'XTick',0:2:10,...  
    'FontUnits','points',...    
    'FontWeight','normal',...
    'FontSize',10,...
    'FontName','Times')
ylabel({'Temperature (K)'},...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times')
xlabel('Length (L)',...
    'FontUnits','points',...
    'interpreter','latex',...   
    'FontWeight','normal',...
    'FontSize',12,...
    'FontName','Times')
legend({'$N = 10$', '$N = 20$', '$N = 40$', '$N = 80$'},...
    'FontUnits','points',...
    'interpreter','latex',...
    'FontSize',12,...
    'FontName','Times',...
    'Location','NorthEast')
print -depsc2 out/heat-plot-velocity10-different-N.eps

%% Suggestion to fix the oscillation problem 

% Use the backward approximation for the fist derivative. 
% This is called the upwind differencing.

%%
function [A, b] = matrix_builder(N, v)
    L=10; kappa = 0.5; k=10; rho= 1; C=1; T_out=300; T_0=400; 
    h = L / N;
    A = zeros(N);
    b = zeros(N, 1);
    A(1, 1:2) = [2 * kappa / h^2, (v * rho * C / (2 * h) - kappa / h^2)];
    b(1) = (kappa / h^2 + v * rho * C / (2 * h)) * T_0;
    for i = 2:N-1
        A(i, i-1:i+1) = [-(kappa / h^2 + v * rho * C / (2 * h)), ...
                         2 * kappa / h^2, ...
                         (v * rho * C / (2 * h) - kappa / h^2)]; 
        b(i) = Q(h * i); 
    end
    A(N, N-2:N) = [1/ (2*h), -2/h, 3/(2 * h) + k/kappa];
    b(N) = k / kappa * T_out;
end

function q = Q(z)
    a = 1; 
    b = 3;
    Q_0=50;
    if z < a || z > b 
        q = 0;
        return 
    end
    q = Q_0 * sin((z - a) * pi / (b - a));
end